### ISSUE TITLE
MatchObjects

### ISSUE THREAD

**Issue by creold** [joshbduncan/adobe-scripts#3]
Hi. Interesting script. Have you thought about adding the option to bring it to a common angle of rotation? E.g. using `BBAccumRotation` tag.

P.S. You have a screenshot in the .md for OffsetObjects from the MatchObjects script

**Comment by joshbduncan** [comment]
That's a great idea! Rotation never crossed my mind. I'll see what I can come up with. Thanks for the suggestion!

P.S. I fixed the README picture link. Got caught blindly copying and pasting 🤦‍♂️...

**Comment by joshbduncan** [comment]
Hey there, I've got a working version in this PR #4 . The updated screenshot won't be live until this is merged as best I can tell so I've included it here so you can see the new option.

So the script will get the rotation of the `source` object (if any) from the BBAccumRotation. It will then iterate through every `target` item, undo it's current rotation (if any) and then apply the `source` rotation. It will then add/update the BBAccumRotation tag on the `target` object.

I tested the operation in a bunch of situations but didn't get crazy with compound paths, clipping masks, and groups yet. They are the usually culprits when things go wrong.

Have a look and let me know what you think? Thanks!

[Here's the sample file I used to test with...](https://www.dropbox.com/s/pxamrzn6csxwco5/match-objects-rotation-play.ai?dl=0)

![match-objects-v2](https://user-images.githubusercontent.com/44387852/172725130-bf38a6b2-32d2-468c-b213-677d371d0eb4.png)

**Comment by creold** [comment]
It seems to work just fine. Quick update. 👍

**Comment by joshbduncan** [comment]
Yeah, I built an entire Save Settings system and dialog in my [ScreenSepMarks.jsx](https://github.com/joshbduncan/adobe-scripts/blob/main/ScreenSepMarks.jsx) script but it was more work than the actual script 🤦 . It saves all of the settings info in the app.preferences. I see you are saving out to a file which is probably a much cleaner solution and yours doesn't muck up the Illustrator preferences file. I wasn't aware you could do that from within Illustrator.

I'm not a classically trained programmer, I'm just a hobbyist figuring it out as I go. Your scripts look great, so I will definitely read through more of them. Thanks again for your suggestions!

![screen-sep-marks](https://user-images.githubusercontent.com/44387852/172880733-ee12c706-e924-4cf2-ae44-65c98eb75035.png)

![save-settings-dialog](https://user-images.githubusercontent.com/44387852/172880769-326709b3-137e-4a00-821e-f914e3a260a6.png)

**Comment by creold** [comment]
I myself work as an illustrator, not a developer :-) I've seen this approach with writing the script settings to `app.preferences`, but realized that this is a lot of code. Writing to a local file is easier. I used to write a list of variable values to .txt as an array. But then I found a nice function from one of the authors for writing an object with keys to json. I've been using it ever since. I place these functions inside a dialog function so that I don't have to pass arguments into them.

**Comment by joshbduncan** [comment]
I played with this earlier today and it's so much easier 👍. I'll definitely swapping out the app.preferences mess and moving to this. I previously had to hack together my own "json type" string and then having to interpret it back into vars. It was a long mess because the script I referenced above has 22 different setting that can be tracked. Thanks so much for the idea!

**Comment by joshbduncan** [comment]
@creold I took your suggestion and switch the save settings function in my ScreenSepMarks.jsx script #5 PR. I'm saving multiple settings in one file as a JSON-ish object. This works really well. Thanks again for the suggestion!
